main: com.cavetale.redgreenlight.RedGreenLightPlugin
name: RedGreenLight

version: 0.1
api-version: 1.19

description: RedGreenLight Plugin
author: StarTux
website: https://github.com/StarTux/RedGreenLight

depend: [Core, Mytems, Area, Fam, Tutor]
softdepend: []

commands:

  redgreenlight:
    aliases: []
    description: Admin Interface
    permission: redgreenlight.admin
    usage: /redgreenlight

permissions:

  redgreenlight.admin:
    description: Use /redgreenlight
    default: op
