main: com.cavetale.redgreenlight.RedGreenLightPlugin
name: RedGreenLight

version: 0.1
api-version: '1.21'

description: RedGreenLight Plugin
author: StarTux
website: https://github.com/StarTux/RedGreenLight

depend: [Core, Mytems, Area, Fam, Tutor]
softdepend: []

commands:

  redgreenlightadmin:
    aliases: [rlgladm]
    description: Admin Interface
    permission: redgreenlight.admin
    usage: /redgreenlight

permissions:

  redgreenlight.admin:
    description: Use /redgreenlight
    default: op

  redgreenlight.debug:
    description: Receive debug messages
    default: false
